import { neon } from '@neondatabase/serverless';
import crypto from 'node:crypto';
const sql=neon(process.env.DATABASE_URL);
const adminEmail=String(process.env.ADMIN_EMAIL||'ghost_eg2003@yahoo.com').trim().toLowerCase();
const json=(res,status,data)=>{res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))};
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return[i>-1?v.slice(0,i):v,i>-1?decodeURIComponent(v.slice(i+1)):'']}));
const tokenHash=t=>crypto.createHash('sha256').update(t).digest('hex');
const makeHash=p=>{const s=crypto.randomBytes(16).toString('hex');return s+':'+crypto.scryptSync(p,s,64).toString('hex')};
const verify=(p,h)=>{const [s,d]=String(h||'').split(':');if(!s||!d)return false;const a=Buffer.from(crypto.scryptSync(p,s,64).toString('hex'),'hex'),b=Buffer.from(d,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)};
async function body(req){if(req.body&&typeof req.body==='object')return req.body;let r='';for await(const c of req)r+=c;try{return r?JSON.parse(r):{}}catch{return{}}}
function setCookie(res,t){res.setHeader('Set-Cookie',`portal_session=${encodeURIComponent(t)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`)}
function clearCookie(res){res.setHeader('Set-Cookie','portal_session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0')}
async function ensureAdmin(){const r=await sql`SELECT id FROM users WHERE lower(email)=${adminEmail} LIMIT 1`;if(!r.length){const p=process.env.ADMIN_BOOTSTRAP_PASSWORD||'123456';await sql`INSERT INTO users(name,email,password_hash,role,status) VALUES('أحمد المغربي',${adminEmail},${makeHash(p)},'coordinator','approved')`}else await sql`UPDATE users SET role='coordinator',status='approved',updated_at=NOW() WHERE lower(email)=${adminEmail}`}
async function current(req){const t=cookies(req).portal_session;if(!t)return null;const r=await sql`SELECT u.id,u.name,u.email,u.role,u.status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=${tokenHash(t)} AND s.expires_at>NOW() LIMIT 1`;return r[0]||null}
async function admin(req,res){const u=await current(req);if(!u||u.role!=='coordinator'||u.status!=='approved'){json(res,403,{ok:false,message:'غير مصرح'});return null}return u}
export default async function handler(req,res){
 if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}
 if(!process.env.DATABASE_URL)return json(res,500,{ok:false,message:'قاعدة البيانات غير مهيأة في Vercel.'});
 try{
  await ensureAdmin();
  const action=String((req.query&&req.query.action)||'').toLowerCase();
  if(req.method==='POST'&&action==='register'){const b=await body(req),name=String(b.name||'').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(name.length<2||!email||password.length<6)return json(res,400,{ok:false,message:'أدخل الاسم والبريد والرقم السري (6 أحرف/أرقام على الأقل).'});if(email===adminEmail)return json(res,409,{ok:false,message:'هذا البريد مخصص لمنسق البوابة.'});if((await sql`SELECT id FROM users WHERE lower(email)=${email} LIMIT 1`).length)return json(res,409,{ok:false,message:'البريد الإلكتروني مستخدم بالفعل.'});await sql`INSERT INTO users(name,email,password_hash,role,status) VALUES(${name},${email},${makeHash(password)},'user','pending')`;return json(res,201,{ok:true,message:'تم إنشاء الحساب، وهو الآن بانتظار موافقة المنسق.'})}
  if(req.method==='POST'&&action==='login'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),r=await sql`SELECT id,name,email,password_hash,role,status FROM users WHERE lower(email)=${email} LIMIT 1`,u=r[0];if(!u||!verify(password,u.password_hash))return json(res,401,{ok:false,message:'بيانات الدخول غير صحيحة'});if(u.status!=='approved')return json(res,403,{ok:false,message:u.status==='rejected'?'تم رفض طلب الدخول. راجع منسق البوابة.':'الحساب بانتظار موافقة المنسق.'});const t=crypto.randomBytes(32).toString('base64url');await sql`INSERT INTO sessions(user_id,token_hash,expires_at) VALUES(${u.id},${tokenHash(t)},NOW()+INTERVAL '7 days')`;setCookie(res,t);return json(res,200,{ok:true,user:{id:u.id,name:u.name,email:u.email,role:u.role}})}
  if(req.method==='POST'&&action==='logout'){const t=cookies(req).portal_session;if(t)await sql`DELETE FROM sessions WHERE token_hash=${tokenHash(t)}`;clearCookie(res);return json(res,200,{ok:true})}
  if(req.method==='GET'&&action==='me'){const u=await current(req);return json(res,200,{ok:true,user:u?{id:u.id,name:u.name,email:u.email,role:u.role}:null})}
  if(req.method==='GET'&&action==='users'){const a=await admin(req,res);if(!a)return;const r=await sql`SELECT id,name,email,role,status,created_at FROM users ORDER BY created_at DESC`;return json(res,200,{ok:true,users:r.filter(x=>x.email.toLowerCase()!==adminEmail)})}
  if(req.method==='POST'&&action==='status'){const a=await admin(req,res);if(!a)return;const b=await body(req),status=['pending','approved','rejected'].includes(b.status)?b.status:null;if(!b.id||!status)return json(res,400,{ok:false,message:'طلب غير صالح'});const t=(await sql`SELECT id,email FROM users WHERE id=${b.id} LIMIT 1`)[0];if(!t||t.email.toLowerCase()===adminEmail)return json(res,400,{ok:false,message:'لا يمكن تعديل هذا الحساب'});await sql`UPDATE users SET status=${status},updated_at=NOW() WHERE id=${b.id}`;await sql`INSERT INTO audit_log(actor_user_id,action,target_user_id,details) VALUES(${a.id},'user_status_change',${b.id},${JSON.stringify({status})}::jsonb)`;return json(res,200,{ok:true})}
  if(req.method==='POST'&&action==='password'){const a=await admin(req,res);if(!a)return;const b=await body(req),p=String(b.password||'');if(!b.id||p.length<6)return json(res,400,{ok:false,message:'الرقم السري يجب أن يكون 6 أحرف أو أرقام على الأقل.'});const t=(await sql`SELECT id,email FROM users WHERE id=${b.id} LIMIT 1`)[0];if(!t||t.email.toLowerCase()===adminEmail)return json(res,400,{ok:false,message:'لا يمكن تعديل هذا الحساب'});await sql`UPDATE users SET password_hash=${makeHash(p)},updated_at=NOW() WHERE id=${b.id}`;await sql`INSERT INTO audit_log(actor_user_id,action,target_user_id) VALUES(${a.id},'password_change',${b.id})`;return json(res,200,{ok:true,message:'تم تغيير الرقم السري بنجاح.'})}
  if(req.method==='DELETE'&&action==='user'){const a=await admin(req,res);if(!a)return;const id=String((req.query&&req.query.id)||'');const t=id?(await sql`SELECT id,email FROM users WHERE id=${id} LIMIT 1`)[0]:null;if(!t||t.email.toLowerCase()===adminEmail)return json(res,400,{ok:false,message:'لا يمكن حذف هذا الحساب'});await sql`DELETE FROM users WHERE id=${id}`;await sql`INSERT INTO audit_log(actor_user_id,action,details) VALUES(${a.id},'user_delete',${JSON.stringify({id})}::jsonb)`;return json(res,200,{ok:true,message:'تم حذف الحساب.'})}
  return json(res,404,{ok:false,message:'المسار غير موجود'})
 }catch(e){console.error(e);return json(res,500,{ok:false,message:'حدث خطأ في الخادم. حاول مرة أخرى.'})}
}